#!/usr/bin/env python3
"""Collect paired QA candidate scores while reusing a precision-matched baseline."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from spc_vlm_runtime import (
    build_candidate_prompt,
    candidate_key,
    load_model_specs,
    score_answer,
)
from evaluate_pope_native import append_jsonl, score_qa_candidates


TaskKey = Tuple[str, str, str]


def read_jsonl(path: str) -> List[Dict[str, Any]]:
    return [
        json.loads(line)
        for line in Path(path).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def question(item: Dict[str, Any]) -> str:
    return str((item.get("direct_qa") or {}).get("question") or "")


def ground_truth(item: Dict[str, Any], side: str) -> str:
    return str((item.get("direct_qa") or {}).get(f"{side}_gt") or "")


def image_path(images_root: str, subcategory: str, pair_id: str, side: str) -> str:
    subdirectory = subcategory.replace(" ", "_").replace("/", "_")
    pair_directory = pair_id.replace(" ", "_")
    filename = "counterfactual.png" if side == "counterfactual" else "commonsense.png"
    return str(Path(images_root) / subdirectory / pair_directory / filename)


def load_baselines(paths: Iterable[Path]) -> Dict[TaskKey, Tuple[str, Dict[str, Any]]]:
    baselines: Dict[TaskKey, Tuple[str, Dict[str, Any]]] = {}
    for path in paths:
        for row in read_jsonl(str(path)):
            revis = row.get("revis") or {}
            if row.get("status") != "ok" or "baseline_prediction" not in revis:
                continue
            key = (str(row.get("pair_id")), str(row.get("task")), str(row.get("side")))
            if not all(key):
                continue
            if key in baselines:
                raise ValueError(f"duplicate baseline row: {key}")
            baselines[key] = (
                str(revis["baseline_prediction"]),
                dict((row.get("raw") or {}).get("baseline_raw") or {}),
            )
    return baselines


def load_completed(path: Path) -> set[TaskKey]:
    if not path.exists():
        return set()
    return {
        (str(row.get("pair_id")), str(row.get("task")), str(row.get("side")))
        for row in read_jsonl(str(path))
        if row.get("status") == "ok"
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Score paired binary QA with a baseline generated by the same model precision."
    )
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--images-root", required=True)
    parser.add_argument("--baseline-results", action="append", required=True)
    parser.add_argument("--models", default="configs/qwen_32b_instruct_bf16_fair.json")
    parser.add_argument("--output", required=True)
    parser.add_argument("--shard-index", type=int, required=True)
    parser.add_argument("--shard-count", type=int, required=True)
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    if not 0 <= args.shard_index < args.shard_count:
        raise SystemExit("shard-index must be in [0, shard-count)")
    specs = load_model_specs(args.models)
    if len(specs) != 1 or specs[0].backend != "transformers":
        raise SystemExit("exactly one transformers model is required per shard")
    spec = specs[0]
    baselines = load_baselines(Path(path) for path in args.baseline_results)

    items = [
        item
        for index, item in enumerate(read_jsonl(args.dataset))
        if index % args.shard_count == args.shard_index
    ]
    tasks: List[Tuple[Dict[str, Any], str]] = []
    for item in items:
        for side in ("commonsense", "counterfactual"):
            tasks.append((item, side))
    selected = tasks
    if args.limit > 0:
        selected = selected[: args.limit]

    output = Path(args.output)
    completed = load_completed(output)
    for position, (item, side) in enumerate(selected, start=1):
        pair_id = str(item.get("pair_id") or "")
        key = (pair_id, "qa", side)
        if key in completed:
            continue
        if key not in baselines:
            raise ValueError(f"missing precision-matched baseline row: {key}")
        baseline_text, baseline_raw = baselines[key]
        baseline_key = candidate_key(spec, "qa", baseline_text)
        current_image_path = image_path(
            args.images_root,
            str(item.get("subcategory") or ""),
            pair_id,
            side,
        )
        candidates, score_ms = score_qa_candidates(
            spec,
            item,
            current_image_path,
            image_preprocessing="model_native",
        )
        gt = ground_truth(item, side)
        cs_gt = ground_truth(item, "commonsense")
        cf_gt = ground_truth(item, "counterfactual")
        candidate_payload = {
            "backend": "local_transformers_qwen3_vl_joint_next_token",
            "model": spec.model,
            "model_precision": {"quantization": spec.quantization, "dtype": spec.dtype},
            "image_preprocessing": "model_native",
            "mitigation": "score_collection_only",
            "scoring_prompt": build_candidate_prompt(question(item)),
            "baseline_pred": baseline_text,
            "baseline_key": baseline_key,
            "image_top": max(candidates, key=lambda row: row["logp_image"])["key"],
            "prior_top": max(candidates, key=lambda row: row["logp_prior"])["key"],
            "candidates": candidates,
        }
        record = {
            "model_name": spec.name,
            "backend": spec.backend,
            "model": spec.model,
            "pair_id": pair_id,
            "cv_group": item.get("cv_group"),
            "category": item.get("category"),
            "subcategory": item.get("subcategory"),
            "task": "qa",
            "side": side,
            "paired_side": "counterfactual" if side == "commonsense" else "commonsense",
            "image_path": current_image_path,
            "status": "ok",
            "question": question(item),
            "gt": gt,
            "cf_gt": cf_gt,
            "cs_gt": cs_gt,
            "pred": baseline_text,
            "correct": bool(score_answer("qa", baseline_text, gt)),
            "commonsense_error": bool(score_answer("qa", baseline_text, cs_gt))
            if side == "counterfactual" and not score_answer("qa", baseline_text, gt)
            else False,
            "score_latency_ms": score_ms,
            "cp_vbc": candidate_payload,
            "raw": {
                "baseline_raw": baseline_raw,
                "cp_vbc": candidate_payload,
                "baseline_source": args.baseline_results,
            },
        }
        append_jsonl(output, record)
        if position % 50 == 0:
            print(f"shard {args.shard_index}: {position}/{len(selected)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
