import json
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest
import torch

BENCHMARK_JSONL = Path("CDH-Bench.revised.strict.jsonl")
EXPOSURE_LEDGER = Path("runtime/paper/cdh_exposure_ledger.json")
requires_benchmark = pytest.mark.skipif(
    not BENCHMARK_JSONL.exists(),
    reason="benchmark annotations are downloaded separately (see README Data)",
)
requires_ledger = pytest.mark.skipif(
    not EXPOSURE_LEDGER.exists(),
    reason="exposure ledger is generated by build_cdh_exposure_ledger.py",
)

from cprc_vlm_runtime import candidate_logprob, candidate_logprobs_shared_prefix
from evaluate_cdh_mc_candidate_scores import (
    make_record,
    mc_candidates,
    mc_prompt,
    split_pair_ids,
)


class Tokenizer:
    tokenizer = None

    def __init__(self):
        self.tokenizer = self

    def __call__(self, text, **_kwargs):
        values = {" A": [1, 2], " B": [1, 3]}[text]
        return {"input_ids": torch.tensor([values], dtype=torch.long)}


class Model:
    def __init__(self):
        self.calls = 0

    def __call__(self, input_ids, **_kwargs):
        self.calls += 1
        logits = torch.arange(8, dtype=torch.float32).repeat(
            1, input_ids.shape[-1], 1
        )
        return SimpleNamespace(logits=logits)


def first_benchmark_item():
    line = Path("CDH-Bench.revised.strict.jsonl").read_text(
        encoding="utf-8"
    ).splitlines()[0]
    return json.loads(line)


@requires_benchmark
def test_mc_prompt_and_candidate_keys_match_the_frozen_evaluator_format():
    item = first_benchmark_item()
    assert mc_candidates(item) == [("A", " A"), ("B", " B"), ("C", " C"), ("D", " D")]
    assert mc_prompt(item, final=True).endswith(
        "Answer with a single letter (A, B, C, or D).\nFinal answer:"
    )


@requires_ledger
def test_exposure_ledger_resolves_disjoint_development_and_unseen_splits():
    manifest = Path("runtime/paper/cdh_exposure_ledger.json")
    development = split_pair_ids(manifest, "cpr_development")
    unseen = split_pair_ids(manifest, "cpr_unseen")
    assert len(development) == 70
    assert len(unseen) == 230
    assert development.isdisjoint(unseen)


def test_shared_prefix_batch_matches_individual_candidate_forwards():
    processor = Tokenizer()
    prompt_inputs = {
        "input_ids": torch.tensor([[5, 6, 7]], dtype=torch.long),
        "attention_mask": torch.ones((1, 3), dtype=torch.long),
    }
    with patch(
        "cprc_vlm_runtime.candidate_vlm_inputs",
        side_effect=lambda *_args, **_kwargs: {
            key: value.clone() for key, value in prompt_inputs.items()
        },
    ):
        shared_model = Model()
        shared = candidate_logprobs_shared_prefix(
            shared_model, processor, "prompt", None, [" A", " B"]
        )
        individual_model = Model()
        individual = [
            candidate_logprob(
                individual_model, processor, "prompt", None, candidate
            )
            for candidate in (" A", " B")
        ]
    assert shared_model.calls == 1
    assert individual_model.calls == 2
    assert shared == individual


@requires_benchmark
def test_record_contains_the_candidate_views_consumed_by_the_analyzer():
    item = first_benchmark_item()
    spec = SimpleNamespace(
        name="Qwen3-VL-30B-A3B-Instruct-BF16",
        backend="transformers",
        model="Qwen3-VL-30B-A3B-Instruct",
        quantization="none",
        dtype="bfloat16",
    )
    candidates = [
        {
            "key": key,
            "text": text,
            "logp_image": image_score,
            "avg_logp_image": image_score,
            "logp_prior": prior_score,
            "avg_logp_prior": prior_score,
            "image_token_count": 1,
            "prior_token_count": 1,
            "image_token_ids": [index],
            "prior_token_ids": [index],
        }
        for index, (key, text, image_score, prior_score) in enumerate(
            [
                ("A", " A", -0.1, -0.2),
                ("B", " B", -0.8, -0.9),
                ("C", " C", -1.0, -1.1),
                ("D", " D", -1.2, -1.3),
            ]
        )
    ]
    row = make_record(
        spec,
        item,
        "commonsense",
        Path("images/example.png"),
        "A",
        1,
        candidates,
        2,
    )
    assert row["status"] == "ok"
    assert row["cp_vbc"]["baseline_key"] == "A"
    assert row["cp_vbc"]["image_top"] == "A"
    assert row["cp_vbc"]["prior_top"] == "A"
    assert len(row["cp_vbc"]["candidates"]) == 4
